#!/bin/bash

##############################
# Working directories
##############################

# Temporary file directory
TMP=state/partition1

# Experiment folder (each discovery run will get its own subfolder under EXPDIR)
EXPDIR=exp

# Feature dimension (39-dim PLP are produced by default)
DIM=39

##############################
# External package executables
##############################

# The sph2pipe sphere unpacking tool
SPH2PIPEBIN=/disk/scratch/s1444673/zero/installs/wav/sph2pipe_v2.5/sph2pipe

# sox, a standard linux tool
SOXBIN=/usr/bin/sox

# feacalc from the ICSI Sprachcore package
FEACALCBIN=/disk/scratch/s1444673/zero/installs/wav/icsi-scenic-tools-20120105/feacalc-0.92/feacalc

##############################
# Grid job parameters
##############################

# Number of files processed per LSH array job task
NJ_LSH=1

# Memory requirements per LSH array job task
MEM_LSH=2G

# Number of file pairs processed per discovery array job task
# Note that N wav files will generate N*(N-1) pairs for processing
NJ_DISC=20

# Memory requirements per discovery array job task
MEM_DISC=8G

