#!/bin/bash

#USAGE: ./post_disc <exp_name> <match_thr>

#
# Copyright 2011-2015  Johns Hopkins University (Author: Aren Jansen)
#

. config

ulimit -c 0

TMP=${TMP:=/tmp}

EXPNAME=$1
DTWTHR=$2
OLAPTHR=$3
DEDUPTHR=$4
DURTHR=$5
MATCHFILE=$6
# VADPATH=$7
EXPDIR=$EXPDIR/$EXPNAME
OUTDIR=$EXPDIR/matches/config$DTWTHR-$OLAPTHR-$DEDUPTHR-$DURTHR
mkdir $OUTDIR
echo $OUTDIR

# # Original settings
# OLAPTHR=0.97
# DEDUPTHR=0.8
# DURTHR=50
# RHOTHR=500

# Modified settings
# OLAPTHR=0.8
# DEDUPTHR=0.8
# DURTHR=20
RHOTHR=500

if [ -z $EXPNAME ]; then
    echo "USAGE: ./post_disc <exp_name> <match_thr>"
    exit
fi

if [ -z $DTWTHR ]; then
    echo "USAGE: ./post_disc <exp_name> <match_thr>"
    exit
fi

if [ ! -d $EXPDIR ]; then
    echo "ERROR: experiment subfolder $EXPDIR does not exist"
    exit
fi

echo "Post-processing experiment $EXPDIR"

echo "Generating master match file: $OUTDIR/master_match"
# cat $EXPDIR/matches/out.* | cut -d ' ' -f1-6 | awk 'NF == 2 || ($6 < rhothr && $5 > dtwthr && $2-$1 > durthr && $4-$3 > durthr) {print $0;}' dtwthr=$DTWTHR durthr=$DURTHR rhothr=$RHOTHR | uniq | awk 'NF == 2 {lastpair=$0; lastNF=2; next;}  lastNF==2 {print lastpair; print $0; lastNF=6; next} {print $0; lastNF=6;}' > $OUTDIR/master_match
echo ls $EXPDIR/matches/$MATCHFILE.*
cat $EXPDIR/matches/$MATCHFILE.* | cut -d ' ' -f1-6 | awk 'NF == 2 || ($6 < rhothr && $5 > dtwthr && $2-$1 > durthr && $4-$3 > durthr) {print $0;}' dtwthr=$DTWTHR durthr=$DURTHR rhothr=$RHOTHR | uniq | awk 'NF == 2 {lastpair=$0; lastNF=2; next;}  lastNF==2 {print lastpair; print $0; lastNF=6; next} {print $0; lastNF=6;}' > $OUTDIR/master_match

echo "Building adjacency graph"
echo python scripts/build_graph.py --input=$OUTDIR/master_match --probthr=$DTWTHR --olapthr=$OLAPTHR --output=$OUTDIR/master_graph --list=$EXPDIR/files.base
python scripts/build_graph.py --input=$OUTDIR/master_match --probthr=$DTWTHR --olapthr=$OLAPTHR --output=$OUTDIR/master_graph --list=$EXPDIR/files.base

echo "Perform clustering"
# python ./scripts/conncomp_dfs.py --input=$OUTDIR/master_graph.edges --output=$OUTDIR/master_graph.clusters --thresh=0
python ./scripts/conncomp_dfs.py --input=$OUTDIR/master_graph.olapedges --output=$OUTDIR/master_graph.clusters --thresh=0
python ./scripts/conncomp_dfs.py --input=$OUTDIR/master_graph.zedges --output=$OUTDIR/master_graph.zclusters --thresh=0

# echo "Dedup clusters"
python scripts/dedup_clusters.py --ninput=$OUTDIR/master_graph.nodes --cinput=$OUTDIR/master_graph.zclusters --dedupthr=$DEDUPTHR --output=$OUTDIR/master_graph.dedups

# echo "Remove garbage clusters"
cat $OUTDIR/master_graph.dedups | awk 'length($0) < 60000 && NF < 10000 {print $0;}' > $OUTDIR/master_graph.dedupsfilt
mv $OUTDIR/master_graph.dedupsfilt $OUTDIR/master_graph.dedups

# # echo "Write the bags-of-pseudoterms feature file"
# # mkdir $EXPDIR/pseudotext/
# # echo python scripts/dump_pseudoterm.py --cinput=$OUTDIR/master_graph.dedups --ninput=$OUTDIR/master_graph.nodes --output=$OUTDIR/master_graph.feats --listname=$EXPDIR/files.base --pseudopath=$EXPDIR/pseudotext/ --vadin=$VADPATH
# # python scripts/dump_pseudoterm.py --cinput=$OUTDIR/master_graph.dedups --ninput=$OUTDIR/master_graph.nodes --output=$OUTDIR/master_graph.feats --listname=$EXPDIR/files.base --pseudopath=$EXPDIR/pseudotext/ --vadin=$VADPATH

# cp $OUTDIR/master_graph.dedups $OUTDIR/master_graph.nodes $OUTDIR/master_graph.feats $EXPDIR/results/
